#!/usr/bin/with-contenv bash

for file in /app/scripts/*; do
	if [ ! -f "$file" ]; then
		continue
	fi
	head -n 1 "$file" | grep -q "^#!" || continue
	target="/usr/local/bin/$(basename "${file%.*}" | tr "_" "-")"
	cat << EOF > "$target"
#!/usr/bin/with-contenv bash
exec s6-setuidgid abc "$file" "\$@"
EOF
	chmod +x "$target"
done
