#!/usr/bin/with-contenv bash

source "/app/scripts/functions.sh"

cd /app

SUCCESS "**** Starting app ****"

if [ "$MODE" != "production" ]; then
	exec s6-setuidgid abc fastapi dev app --host 0.0.0.0
else
	exec s6-setuidgid abc fastapi run app --host 0.0.0.0
fi
